# Generated by Django 4.2.7 on 2023-12-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
