# Generated by Django 4.2.7 on 2023-12-28 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
        ("product", "0008_product_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="order.order",
            ),
        ),
        migrations.AddField(
            model_name="productitem",
            name="status",
            field=models.IntegerField(
                choices=[(0, "BASKET"), (1, "CHECKOUT"), (2, "DONE")], default=0
            ),
        ),
    ]
