# Generated by Django 4.2.7 on 2024-01-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0009_productitem_order_productitem_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
