# Generated by Django 4.2.7 on 2024-01-05 07:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("product", "0012_alter_comment_options_alter_productitem_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productitem",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_items",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
