# Generated by Django 4.2.7 on 2024-01-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_productitem_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="has_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="old_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="əvvəlki qiymət",
            ),
        ),
    ]
