# Generated by Django 4.2.7 on 2023-11-19 00:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="request",
            options={"verbose_name": "Request", "verbose_name_plural": "Requests"},
        ),
        migrations.AddField(
            model_name="request",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
